### ISSUE TITLE
TensorRT Output always gives the same random string

### ISSUE THREAD

**Issue by AbhiHegde3004** [bharatsubedi/PARseq_torch#1]
Hi,

I used the same repo to convert the pth to onnx. when i convert onnx to trt and infer it always gives the same output no matter what is the output.

Any idea on how to solve this ?

**Comment by lerndeep** [comment]
@AbhiHegde3004 have you trained your module using this repo or not?

**Comment by bharatsubedi** [comment]
@AbhiHegde3004 have you solved issues? I never faced those type of issue.

**Comment by AbhiHegde3004** [comment]
I used prertrained model itself . 
Later I found i need to have correct version of pytorch. Somehow tensorrt is not giving a very good results , especially predicting the end character.

**Comment by bharatsubedi** [comment]
@AbhiHegde3004 if you use my code for training, and set the environment properly, I hope you will not get any problems in accuracy in tensorrt, onnx and pure pytorch version.

**Comment by AbhiHegde3004** [comment]
Ok thanks .. let me try again
