### ISSUE TITLE
pytorch-onnx 

### ISSUE THREAD

**Issue by Ehteshamciitwah** [bharatsubedi/PARseq_torch#2]
Hello, thank you for your work. During converting the model from pytorch to onnx. I am facing an error.
RuntimeError: input_shape.size() > 0 || reshape.size() > 0INTERNAL ASSERT FAILED at "..\\torch\\csrc\\jit\\passes\\onnx\\shape_type_inference.cpp":448, please report a bug to PyTorch. Reshape node should have at least one input size > 0 when constant folding.

Could you please share your thoughts. Thank you

**Comment by bharatsubedi** [comment]
@Ehteshamciitwah this is due to your environmental problem, not a code issue. I think if you update onnx version will solve the problem.

**Comment by bharatsubedi** [comment]
@Ehteshamciitwah if you want to use this code first train your custom dataset with this code and convert onnx and tensorrt. And please do not send a private messages in emails.
