### ISSUE TITLE
ONNX and TRT results

### ISSUE THREAD

**Issue by Ehteshamciitwah** [bharatsubedi/PARseq_torch#3]
Hello,
I am just curious how you convert pytorch into onnx and TRT with original forward function. Because the original forward function has a break point that depends on the input image. while during conversion to onnx, onnx only follows tracing. Did you use decoder_ar=False during conversion? Because with decoder_ar=True the onnx model bounds to only that input image. 
Secondly, with decoder_ar=False , we can successfully convert model to onnx and TRT but the inference results are not the same as in authors paper. Kindly share your thoughts. Please mentioned the TRT version. Thank you

**Comment by bharatsubedi** [comment]
@Ehteshamciitwah I tried with decoder_ar=True and batch size 1. when I tried with dynamic batch size result not good.

**Comment by Ehteshamciitwah** [comment]
Thank you for your timely response. 
As per your direction, I comment line 163,164 and covert to onnx and check results. Results are the same. But when I am converting to TRT it shows an Argmax node problem because of line 138 tgt_in[:, j] = p_i.squeeze().argmax(-1). How did You convert to TRT and what was your TRT version? Thank you

**Comment by AbhiHegde3004** [comment]
@Ehteshamciitwah 

If u are getting the error on the argmax node then -> work around is just export with different batch size. it will get converted to tensorrt engine correctly. I faced the same issue then i have solved it using this method of exporting to onnx with different batch size > 1 . Not sure why or the reason behind it

**Comment by Ehteshamciitwah** [comment]
Thank you for your comment. Can you please elaborate following queries. 
which torch version you used?
Did you do any changes in the original forward such as break point or argmax.
Did you use onnx simplify 0.4.13 for simplify onnx before conversion to TRT.
Which TRT version used conversion?
Thank you.

**Comment by AbhiHegde3004** [comment]
pytorch = 1.13.1
Tensorrt = 8.5.1.3
onnx = 1.13.1 
onnxsim  = 0.4.17

yes i used onnxsim before converting to the TRT. 

i had to use batch size > 1 while exporting to onnx, I have put batch size as 8 in my case
Did you do any changes in the original forward such as break point or argmax. - **No**

**Comment by Ehteshamciitwah** [comment]
Thank you for comment @AbhiHegde3004 . I solved the problem of batch=1 by changing tgt_in[:, j] = p_i.squeeze(1).argmax(-1). With TRT 8.4 and 8.5 its working well. Thank you
